# Nome da aplicação
spring.application.name=leazor-backend

# Configurações do H2 Database
spring.datasource.url=jdbc:h2:mem:leazordb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Permite que o Spring crie e atualize as tabelas automaticamente
spring.jpa.hibernate.ddl-auto=update

# Mostra no console o SQL que o Hibernate está executando (ótimo para estudos e debug)
spring.jpa.show-sql=true

# Habilita o console do H2 no navegador
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console