# Nome da aplicação
spring.application.name=leazor-backend

# ---------------------------------------------------------
# CONFIGURAÇÃO SQL SERVER (PRODUÇÃO / DEV)
# ---------------------------------------------------------
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=leazordb;encrypt=true;trustServerCertificate=true;
# Coloque seu usuário do SQL Server (geralmente 'sa')
spring.datasource.username=sa
# Coloque a senha do seu SQL Server
spring.datasource.password=Thalmeida07@
spring.datasource.driverClassName=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect
mqtt.broker.url=tcp://localhost:1883
mqtt.client.id=leazor-backend

# --------------------------------------------------------
# CONFIGURAÇÃO H2 (Desativada - Remova os '#' para usar novamente)
# ---------------------------------------------------------
# spring.datasource.url=jdbc:h2:mem:leazordb
# spring.datasource.driverClassName=org.h2.Driver
# spring.datasource.username=sa
# spring.datasource.password=
# spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
# spring.h2.console.enabled=true
# spring.h2.console.path=/h2-console

# ---------------------------------------------------------
# CONFIGURAÇÕES DO HIBERNATE
# ---------------------------------------------------------
# Atualiza as tabelas automaticamente sem apagar os dados
spring.jpa.hibernate.ddl-auto=update
# Exibe o SQL no console para facilitar o debug
spring.jpa.show-sql=true